<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "translation_tools"
 *
 * Auto generated by Extension Builder 2015-03-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Translation tools',
	'description' => 'Translation tools',
	'category' => 'module',
	'author' => 'R3 H6',
	'author_email' => 'r3h6@outlook.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);