<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "l10n_overwrite"
 *
 * Auto generated by Extension Builder 2015-01-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'L10N  overwrite',
	'description' => 'Overwrites the default language files. (Auto created by extension translation_tools.)',
	'category' => 'misc',
	'author' => 'R3 H6',
	'author_email' => 'r3h6@outlook.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);